// <auto-generated />
using System;
using EFDataAccessLibary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDataAccessLibrary.Migrations
{
    [DbContext(typeof(AmazonaContext))]
    [Migration("20220314130039_UpdatingOrderSchemas")]
    partial class UpdatingOrderSchemas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFDataAccessLibary.Models.Product", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"), 1L, 1);

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("countInStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("createdAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("numReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<float>("rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("updatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("_id");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            _id = 1,
                            brand = "Nike",
                            category = "Shirts",
                            countInStock = 20,
                            description = "A popular shirt",
                            image = "/images/shirt1.jpg",
                            name = "Free Shirt",
                            numReviews = 10,
                            price = 70f,
                            rating = 4.5f,
                            slug = "free-shirt"
                        },
                        new
                        {
                            _id = 2,
                            brand = "Adidas",
                            category = "Shirts",
                            countInStock = 20,
                            description = "A popular shirt",
                            image = "/images/shirt2.jpg",
                            name = "Fit Shirt",
                            numReviews = 10,
                            price = 80f,
                            rating = 4.2f,
                            slug = "fit-shirt"
                        },
                        new
                        {
                            _id = 3,
                            brand = "Raymond",
                            category = "Shirts",
                            countInStock = 20,
                            description = "A popular shirt",
                            image = "/images/shirt3.jpg",
                            name = "Slim Shirt",
                            numReviews = 10,
                            price = 90f,
                            rating = 4.5f,
                            slug = "slim-shirt"
                        },
                        new
                        {
                            _id = 4,
                            brand = "Oliver",
                            category = "Pants",
                            countInStock = 20,
                            description = "Smart looking pants",
                            image = "/images/pants1.jpg",
                            name = "Golf Pants",
                            numReviews = 10,
                            price = 90f,
                            rating = 4.5f,
                            slug = "golf-pants"
                        },
                        new
                        {
                            _id = 5,
                            brand = "Zara",
                            category = "Pants",
                            countInStock = 20,
                            description = "A popular pants",
                            image = "/images/pants2.jpg",
                            name = "Fit Pants",
                            numReviews = 10,
                            price = 95f,
                            rating = 4.5f,
                            slug = "fit-pants"
                        },
                        new
                        {
                            _id = 6,
                            brand = "Casely",
                            category = "Pants",
                            countInStock = 20,
                            description = "A popular pants",
                            image = "/images/pants3.jpg",
                            name = "Classic Pants",
                            numReviews = 10,
                            price = 75f,
                            rating = 4.5f,
                            slug = "classic-pants"
                        });
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.Order", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"), 1L, 1);

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("deliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("isPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("itemsPrice")
                        .HasColumnType("real");

                    b.Property<DateTime?>("paidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("shippingAddressId")
                        .HasColumnType("int");

                    b.Property<float>("shippingPrice")
                        .HasColumnType("real");

                    b.Property<float>("taxPrice")
                        .HasColumnType("real");

                    b.Property<float>("totalPrice")
                        .HasColumnType("real");

                    b.Property<DateTime?>("updatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("_id");

                    b.HasIndex("shippingAddressId");

                    b.HasIndex("userId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.OrderDetail", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"), 1L, 1);

                    b.Property<string>("image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("_id");

                    b.HasIndex("orderId");

                    b.HasIndex("productId");

                    b.ToTable("ordersDetails", (string)null);
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.ShippingAddress", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"), 1L, 1);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("postalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("_id");

                    b.ToTable("shippingAddresses", (string)null);
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.User", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"), 1L, 1);

                    b.Property<DateTime?>("createdAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("updatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            _id = 1,
                            email = "admin@example.com",
                            isAdmin = true,
                            name = "John",
                            password = "$2a$13$ttXzNqSMImUWGZp4E5h15u9M.hULLd9Z25JwYiTHvyQzB4V2zvNm."
                        },
                        new
                        {
                            _id = 2,
                            email = "user@example.com",
                            isAdmin = false,
                            name = "Jane",
                            password = "$2a$13$Qzq4ggKdTXcaoV8SmFSktuIGpZP7Qwi00zv68LJ83hma8T8Csu7Ve"
                        });
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.Order", b =>
                {
                    b.HasOne("EFDataAccessLibrary.Models.ShippingAddress", "shippingAddress")
                        .WithMany()
                        .HasForeignKey("shippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFDataAccessLibrary.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shippingAddress");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.OrderDetail", b =>
                {
                    b.HasOne("EFDataAccessLibrary.Models.Order", "order")
                        .WithMany("details")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFDataAccessLibary.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.Order", b =>
                {
                    b.Navigation("details");
                });
#pragma warning restore 612, 618
        }
    }
}
